[project]
name = "comfyui-easyocr"
description = "Easy-OCR text recognition and YOLO-based speech/thought-bubble detection for inpainting."
version = "1.1.0"
license = "LICENSE"
dependencies = ["easyocr", "ultralytics"]

[project.urls]
Repository = "https://github.com/prodogape/ComfyUI-EasyOCR"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "prodogape"
DisplayName = "ComfyUI-EasyOCR"
Icon = "https://avatars.githubusercontent.com/u/89724016?s=400&u=cd218743591faf329d4b4f07a14de1130a9f56cc&v=4"
